DROP TABLE IF EXISTS dataservice.error_features;

CREATE TABLE dataservice.error_features (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

INSERT INTO dataservice.error_features (id, name) VALUES (1, 'Baseline feature');

ALTER TABLE dataservice.error_features ALTER COLUMN id RESTART WITH 2;
