DROP TABLE IF EXISTS dataservice.modify_features;

CREATE TABLE dataservice.modify_features (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category text NOT NULL,
    geom geometry(POINT, 2056) NOT NULL
);

INSERT INTO dataservice.modify_features (id, name, category, geom) VALUES (
    1,
    'Existing feature',
    'baseline',
    ST_SetSRID(ST_MakePoint(2600000, 1200000), 2056)
);

ALTER TABLE dataservice.modify_features ALTER COLUMN id RESTART WITH 2;
